---
title: Derivatives
author: Jeremy Buss
date: '2022-04-09'
slug: []
categories: 
  - Calculus
draft: no
katex: yes
---
\(\gdef\ddx{\frac{d}{dx}}\)
\(\gdef\fx{f(x)}\)
\(\gdef\fpx{f'(x)}\)

The following are my personal notes from relearning calculus using the following resources:

- [Khan Academy AP Calculus BC](https://www.khanacademy.org/math/ap-calculus-bc)
- [Paul's Online Notes](https://tutorial.math.lamar.edu/)
taking the online class: [Introduction to Linear Algebra - MIT OCW 18.06](https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/index.htm)

## Definition and Notation
- If \(y=f(x)\) then the derivative is defined to be \(f'(x) = \displaystyle{\lim_{h \rightarrow 0}} \frac{f(x+h)-f(x)}{h}\)
- If \(y=f(x)\) then all of the following are equivalent notations for the derivative: \(f'(x)=y'=\frac{df}{dx}=\frac{dy}{dx}=\frac{d}{dx}(f(x))=Df(x)\)
- If \(y=f(x)\) then all of the following are equivalent notations for derivative evaluated at \(x=a\):
\(f'(a)=y'\vert_{x=a}=\frac{df}{dx}\biggm\vert_{x=a}=\frac{dy}{dx}\biggm\vert_{x=a}=Df(a)\)

## Interpretation of the Derivative
1. If \(y=f(x)\) then \(m=f'(a)\) is the slope of the tangent line to \(y=f(x)\) at \(x=a\)
2. \(f'(a)\) is the instantaneous rate of change of \(f(x)\) at \(x=a\)
3. If \(f(x)\) is the position of an object at time \(x\) then \(f'(a)\) is the velocity of the object at \(x=a\)


## Basic Properties and Formulas
If \(f(x)\) and \(g(x)\) are differentiable functions (the derivative exists), \(c\) and \(n\) are any real numbers:

- Scalar Multiplication: \((cf(x))'=c(f'(x))\)
- Sum: \((f(x)\pm g(x))'=f'(x)\pm g'(x)\)
- Product Rule: \((f(x)g(x))'=f(x)'g(x)+ f(x)g'(x)\)
- Quotient Rule: \(\frac{d}{dx} \left ( \frac{f(x)}{g(x)}\right ) = \frac{f(x)'g(x) - f(x)g'(x)}{[g(x)]^2} \)
- Constant: \(\frac{d}{dx}(c)=0\)
- Power Rule: \(\frac{d}{dx}(x^n)=nx^{n-1}\)
- Chain Rule: \(\frac{d}{dx}(f(g(x)))=f'(g(x))g'(x)\)


## Common Derivatives

- \(\ddx(x)=1\)
- \(\ddx(\sin x)=\cos x\)
- \(\ddx(\cos x) = -\sin x\)
- \(\ddx(\tan x) = \sec ^2 x\)
- \(\ddx(\sec x) = \sec x \tan x  \)
- \(\ddx(\csc x) = -\csc x \cot x \)
- \(\ddx( \cot x) = -\csc^2 x \)
- \(\ddx( \sin ^{-1} x) = \frac{1}{\sqrt{1-x^2}}\)

- \(\ddx( \cos ^{-1} x) = - \frac{1}{\sqrt{1-x^2}}\)
- \(\ddx( \tan^{-1} x) = \frac{1}{1+x^2}\)
- \(\ddx( a^x) = a^x \ln (a)\)
- \(\ddx(\textrm{e}^x) = \textrm{e}^x \)
- \(\ddx(\ln(x)) = \frac{1}{x},\; x>0 \)
- \(\ddx(\ln \vert x \vert) = \frac{1}{x},\; x \ne 0\)
- \(\ddx(\log_a(x)) = \frac{1}{x \ln {a}}, \; x > 0 \)

## Chain Rule Variants

- \(\ddx([\fx^n]) = n[\fx]^{n-1} \fpx  \)
- \(\ddx \left ( \textrm{e}^{\fx} \right ) = \fpx \textrm{e}^{\fx} \)
- \(\ddx(\ln[\fx]) =\frac{\fpx}{\fx} \)
- \(\ddx(\sin[\fx]) = \fpx \cos [\fx]\)
- \(\ddx(\cos [\fx]) = -\fpx\sin[\fx] \)
- \(\ddx(\tan[\fx]) = \fpx \sec^2[\fx]\)
- \(\ddx(\sec[\fx]) = \fpx \sec[\fx]\tan[\fx]\)
- \(\ddx(\tan ^{-1}[\fx]) = \frac{\fpx}{1 + [\fx]^2} \)

## Higher Order Derivatives

- Second Derivative is denoted as \( f''(x)=f^{(2)}(x) = \frac{d^2f}{dx^2} \)
- Second Derivative is defined as \( f''(x)=(\fpx)'\) i.e. the derivative of the first derivative, \(\fpx\)
- nth Derivative is denoted as \( f^{(n)}(x) = \frac{d^nf}{dx^n} \)
- nth Derivative is defined as \( f^{(n)}(x)=(f^{(n-1)}(x))'\) i.e. the derivative of the \((n-1)^{\text{st}}\) derivative, \(f^{(n-1)}(x)\)

## Critical Points

- \( x=c \) is a critical point of \( f(x) \) provided either:
  1. \( f'(c)=0 \)
  2. \( f'(c) \) doesn't exist

## Increasing/Decreasing
- If \(\fpx>0\) for all \(x\) in an interval \(I\) then \(\fx\) is increasing on the interval \(I\)
- If \(\fpx<0\) for all \(x\) in an interval \(I\) then \(\fx\) is decreasing on the interval \(I\)
- If \(\fpx=0\) for all \(x\) in an interval \(I\) then \(\fx\) is constant on the interval \(I\)

## Concave Up/Concave Down
- If \(f''(x)>0\) for all \(x\) in an interval \(I\) then \(\fx\) is concave up on the interval \(I\)
- If \(f''(x)<0\) for all \(x\) in an interval \(I\) then \(\fx\) is concave down on the interval \(I\)

## Inflection Points
- \( x=c \) is an inflection point of \( f(x) \) if the concavity changes at \( x=c \)

## Extrema
- \( x=c \) is an absolute maximum of \( f(x) \) if \( f(c) \ge \fx \) for all \(x\) in the domain
- \( x=c \) is an absolute minimum of \( f(x) \) if \( f(c) \le \fx \) for all \(x\) in the domain
- Fermat's Theorem: If \( f(x) \) has a relative (or local) extrema at \(x=c\), then \(x=c\) is a critical point of \(\fx\)
- Extreme Value Theorem: If \( f(x) \) is continuous on the closed interval \([a,b]\) then there exist numbers \(c\) and \(d\) so that:
  1. \(a \le c, d \le b\)
  2. \(f(c)\) is the absolute max in \([a,b]\)
  3. \(f(d)\) is the absolute max in \([a,b]\)
- Finding Absolute Extrema: To find absolute extrema of the continuous function \(\fx\) on the interval \([a,b]\) use the following:
  1. Find all critical points of \(\fx\) in \([a,b]\)
  2. Evaluate \(\fx\) at all points found in step 1
  3. Evaluate \(f(a)\) and \(f(b)\)
  4. Identify the absolute max and absolute miniumum from evaluations in steps 2 & 3
- \( x=c \) is a relative (or local) maximum of \( f(x) \) if \( f(c) \ge \fx \) for all \(x\) near \(c\)
- \( x=c \) is a relative (or local) minimum of \( f(x) \) if \( f(c) \le \fx \) for all \(x\) near \(c\)
- First Derivative Test: If \( x=c \) is a critical point of \( f(x) \) then \( x=c \) is:
  1. a relative maximum of \( \fx \) if \(\fpx >0 \) to the left of \( x=c \) and \(\fpx <0 \) to the right of \( x=c \)
  2. a relative minimum of \( \fx \) if \(\fpx <0 \) to the left of \( x=c \) and \(\fpx >0 \) to the right of \( x=c \)
  3. Not a relative extrema of \(\fx\) if \(\fpx\) is the same sign on both sides of \(x=c\)
- Second Derivative Test: If \( x=c \) is a critical point of \( f(x) \) such that \(f'(c)=0\) then \( x=c \) is:
  1. a relative maximum of \( \fx \) if \(f''(c)<0 \)
  2. a relative minimum of \( \fx \) if \(f''(c)>0 \)
  3. may be a relative maximum, relative minimum, or neigher if \(f''(c)=0 \)
- Finding Relative Extrema and/or Classify Critical Points:
  1. Find all critical points of \(\fx\)
  2. Use the first derivative test or the second derivative test on each critical point
- Mean Value Theorem: If \(\fx\) is continuous on the closed interval \([a,b]\) and differentiable on the open interval \( (a,b) \) then there is a number \( a < c< b\) such that \(f'(c)= \frac{f(b)-f(a)}{b-a}\)
- Newton's Method: If \(x_n\) is the \(n^{\text{th}}\) guess for the root/solution of \(\fx=0\) then \((n+1)^{st}\) guess is \(x_{n+1}=x_n - \frac{f(x_n)}{f'(x_n)}\) provided \(f'(x_n)\) exists